# Generated by Django 4.0.6 on 2022-08-01 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='price',
        ),
        migrations.AddField(
            model_name='deal',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 8, 54, 50, 865759)),
        ),
        migrations.AddField(
            model_name='deal',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='ruble_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='table_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='usa_dollar_price',
            field=models.IntegerField(default=1),
        ),
    ]
