# Generated by Django 4.0.6 on 2022-08-02 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_remove_deal_price_deal_delivery_time_deal_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValutaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FR', 'USA_dollar')], max_length=120)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 14, 1, 33, 566885)),
        ),
    ]
