# Generated by Django 4.0.6 on 2022-08-03 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_valutarate_alter_deal_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 7, 48, 24, 146272)),
        ),
    ]
