# Generated by Django 4.0.6 on 2022-08-03 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_alter_deal_delivery_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValutaRate',
        ),
        migrations.AlterField(
            model_name='deal',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 8, 58, 41, 562000)),
        ),
    ]
